- hosts: app
  become: yes
  tasks:
  - name: installing the mysql DB
    yum: 
      name: mysql-server 
      state: latest
  - name: Ensure mysql is running
    service: 
      name: mysql 
      state: started
  - name: mysql-python is need to installed
    apt:
      name: python-mysqldb
      state: present
  - name: create db
    mysql_db:
      name: devops
      state: present
  - name: create an user harish
    mysql_user:
      name: harish
      password: harish@123
      priv: '*.*:ALL'
      state: present

